version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: ./docker/node/Dockerfile
    image: portofolio.me/node:10.24.1
    container_name: portofolio-v1.app
    restart: unless-stopped
    tty: true
    environment:
      TZ : Asia/Jakarta
    working_dir: /app
    network_mode: bridge
    ports:
      - 1004:5000