version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: ./docker/node/Dockerfile
    image: portofolio.me/node:10.24.1
    container_name: app.portofolio
    restart: unless-stopped
    tty: true
    environment:
      TZ : Asia/Jakarta
    working_dir: /app
    networks:
      - portofolio-networks
    ports:
      - 1004:5000

#Networks
networks:
  portofolio-networks:
    driver: bridge
    name: portofolio-networks